import { Camiseta } from './models';

export const camisetas: Camiseta[] = [
  {
    id: 1,
    nome: 'Camiseta Azul',
    imagem: 'https://via.placeholder.com/300',
    preco: 29.99,
    tamanhos: ['S', 'M', 'L'],
    cores: ['Azul', 'Branco'],
  },
  {
    id: 2,
    nome: 'Camiseta Vermelha',
    imagem: 'https://via.placeholder.com/300',
    preco: 24.99,
    tamanhos: ['S', 'M', 'XL'],
    cores: ['Vermelho', 'Preto'],
  },
  {
    id: 3,
    nome: 'Camiseta Azul',
    imagem: 'https://via.placeholder.com/300?text=Camiseta+Azul',
    preco: 29.99,
    tamanhos: ['S', 'M', 'L'],
    cores: ['Azul', 'Branco'],
  },
  {
    id: 4,
    nome: 'Camiseta Verde',
    imagem: 'https://via.placeholder.com/300?text=Camiseta+Verde',
    preco: 34.99,
    tamanhos: ['M', 'L', 'XL'],
    cores: ['Verde', 'Preto'],
  },
  {
    id: 5,
    nome: 'Camiseta Amarela',
    imagem: 'https://via.placeholder.com/300?text=Camiseta+Amarela',
    preco: 27.99,
    tamanhos: ['S', 'XL'],
    cores: ['Amarelo', 'Branco'],
  },
  {
    id: 6,
    nome: 'Camiseta Branca',
    imagem: 'https://via.placeholder.com/300?text=Camiseta+Branca',
    preco: 31.99,
    tamanhos: ['M', 'L'],
    cores: ['Branco', 'Azul'],
  },
  {
    id: 7,
    nome: 'Camiseta Preta',
    imagem: 'https://via.placeholder.com/300?text=Camiseta+Preta',
    preco: 25.99,
    tamanhos: ['S', 'M', 'L'],
    cores: ['Preto', 'Vermelho'],
  },
  {
    id: 8,
    nome: 'Camiseta Vermelha',
    imagem: 'https://via.placeholder.com/300?text=Camiseta+Vermelha',
    preco: 32.99,
    tamanhos: ['M', 'L'],
    cores: ['Vermelho', 'Preto'],
  },
  {
    id: 9,
    nome: 'Camiseta Cinza',
    imagem: 'https://via.placeholder.com/300?text=Camiseta+Cinza',
    preco: 29.99,
    tamanhos: ['S', 'M', 'XL'],
    cores: ['Cinza', 'Preto'],
  },
  {
    id: 10,
    nome: 'Camiseta Rosa',
    imagem: 'https://via.placeholder.com/300?text=Camiseta+Rosa',
    preco: 27.99,
    tamanhos: ['S', 'M'],
    cores: ['Rosa', 'Branco'],
  },
  {
    id: 11,
    nome: 'Camiseta Roxa',
    imagem: 'https://via.placeholder.com/300?text=Camiseta+Roxa',
    preco: 26.99,
    tamanhos: ['M', 'L'],
    cores: ['Roxo', 'Preto'],
  },
  {
    id: 12,
    nome: 'Camiseta Laranja',
    imagem: 'https://via.placeholder.com/300?text=Camiseta+Laranja',
    preco: 28.99,
    tamanhos: ['S', 'L'],
    cores: ['Laranja', 'Branco'],
  }
];